### ISSUE TITLE
Add a way to reach warnings

### ISSUE THREAD

**Issue by semanticfire** [theseer/fXSL#2]
libxml_get_last_error only returns Fatal errors, this is the right approach to throw exceptions, since the processing doesn't continue.

libxml_get_errors however also returns warnings, which can be extremly helpfull in debugging unexpected results. e.g. namespace mixup etc. these are in general not fatal so they won't cause a exception.

would it be a option to record all the errors with libxml_get_errors after processing and add a method to fXSLT to reach them ?

**Comment by theseer** [comment]
Sure thing. Will implement it on my travel upcoming Wednesday. Thanks for the input!

**Comment by theseer** [comment]
I adjusted the error detection. For whatever reason not all errors seem to caught from libxml_get_last_error() but using libxml_get_errors() works. Fixed with commit cb57870
