### ISSUE TITLE
Add packagist automatic hook

### ISSUE THREAD

**Issue by nicolopignatelli** [theseer/fXSL#4]
Tagged versions are not automatically available on packagist, please add the proper hook.

**Comment by nicolopignatelli** [comment]
Actually, I verified that every release lacks of a `composer.json` file. Is there a particular reason for this?

**Comment by theseer** [comment]
Yes, there simply was no composer.json in any of the previously released versions because back in those days composer didn't even exist.

Since a composer.json was added there was no new release since nothing else changed.

**Comment by nicolopignatelli** [comment]
I see, thank you for explaining.

**Comment by theseer** [comment]
No problem.

For now using dev-master should work just fine. I don't see any missing features right now hence no scheduled new relesaes. Might change of course, but so far there is not really anything I have on my todo list for fXSL.
